In [1]:
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd

ModuleNotFoundError: No module named 'numpy'

In [14]:
data = pd.read_csv("./Data/NASA_Exoplanet_Archive_Data.csv")
data.head()

,pl_name,hostname,default_flag,sy_snum,sy_pnum,discoverymethod,disc_year,disc_facility,soltype,pl_refname,...,sy_vmagerr2,sy_kmag,sy_kmagerr1,sy_kmagerr2,sy_gaiamag,sy_gaiamagerr1,sy_gaiamagerr2,rowupdate,pl_pubdate,releasedate
0,11 Com b,11 Com,0,2,1,Radial Velocity,2007,Xinglong Station,Published Confirmed,https://ui.adsabs.harvard.edu/abs/2011ApJ...73...,...,-0.023,2.282,0.346,-0.346,4.44038,0.003848,-0.003848,2014-07-23,2011-08,2014-07-23
1,11 Com b,11 Com,0,2,1,Radial Velocity,2007,Xinglong Station,Published Confirmed,https://ui.adsabs.harvard.edu/abs/2008ApJ...67...,...,-0.023,2.282,0.346,-0.346,4.44038,0.003848,-0.003848,2014-05-14,2008-01,2014-05-14
2,11 Com b,11 Com,1,2,1,Radial Velocity,2007,Xinglong Station,Published Confirmed,https://ui.adsabs.harvard.edu/abs/2023arXiv230...,...,-0.023,2.282,0.346,-0.346,4.44038,0.003848,-0.003848,2023-09-19,2023-08,2023-09-19
3,11 UMi b,11 UMi,1,1,1,Radial Velocity,2009,Thueringer Landessternwarte Tautenburg,Published Confirmed,https://ui.adsabs.harvard.edu/abs/2017AJ....15...,...,-0.005,1.939,0.270,-0.270,4.56216,0.003903,-0.003903,2018-09-04,2017-03,2018-09-06
4,11 UMi b,11 UMi,0,1,1,Radial Velocity,2009,Thueringer Landessternwarte Tautenburg,Published Confirmed,https://ui.adsabs.harvard.edu/abs/2011ApJ...73...,...,-0.005,1.939,0.270,-0.270,4.56216,0.003903,-0.003903,2018-04-25,2011-08,2014-07-23

In [13]:
# Informacion de estadisticas descriptivas
data.describe()

,default_flag,sy_snum,sy_pnum,disc_year,pl_orbper,pl_orbpererr1,pl_orbpererr2,pl_orbperlim,pl_orbsmax,pl_orbsmaxerr1,...,sy_disterr2,sy_vmag,sy_vmagerr1,sy_vmagerr2,sy_kmag,sy_kmagerr1,sy_kmagerr2,sy_gaiamag,sy_gaiamagerr1,sy_gaiamagerr2
count,36418.000000,36418.000000,36418.000000,36418.000000,3.324700e+04,3.170900e+04,3.170800e+04,33247.000000,19990.000000,5544.000000,...,34751.000000,35698.000000,35685.000000,35684.000000,35686.000000,35470.000000,35470.000000,35399.000000,35399.000000,35399.000000
mean,0.158081,1.085837,1.881789,2015.413257,1.313046e+04,1.520092e+04,-3.580263e+03,-0.000241,5.017155,1.368994,...,-37.471236,13.595405,0.117140,-0.117769,11.572275,0.036123,-0.035606,13.360688,0.000523,-0.000523
std,0.364822,0.310177,1.203423,3.899352,2.205982e+06,2.639599e+06,5.628794e+05,0.020519,189.502483,70.082416,...,176.837890,2.426546,0.151986,0.182873,2.328657,0.205934,0.197644,2.362041,0.001067,0.001067
min,0.000000,1.000000,1.000000,1992.000000,9.070629e-02,0.000000e+00,-1.000000e+08,-1.000000,0.004400,0.000000,...,-2900.000000,0.872000,0.001000,-12.270000,-3.044000,0.011000,-11.140000,2.364310,0.000118,-0.063232
25%,0.000000,1.000000,1.000000,2014.000000,4.354093e+00,7.990000e-06,-2.000000e-04,0.000000,0.054032,0.000890,...,-21.340000,12.598000,0.046000,-0.137000,10.727500,0.020000,-0.034000,12.395600,0.000255,-0.000508
50%,0.000000,1.000000,1.000000,2016.000000,1.033116e+01,3.800000e-05,-3.800000e-05,0.000000,0.100400,0.003000,...,-7.782500,14.205000,0.092000,-0.092000,12.288000,0.024000,-0.024000,14.017800,0.000356,-0.000356
75%,0.000000,1.000000,2.000000,2016.000000,2.654884e+01,2.000000e-04,-7.990000e-06,0.000000,0.219300,0.051250,...,-2.199000,15.284000,0.137000,-0.046000,13.175000,0.034000,-0.020000,15.056900,0.000508,-0.000255
max,1.000000,4.000000,8.000000,2024.000000,4.020000e+08,4.700000e+08,0.000000e+00,1.000000,19000.000000,5205.000000,...,2700.000000,45.340000,11.000000,-0.001000,35.330000,9.995000,-0.011000,20.186100,0.063232,-0.000118

In [15]:
# Informacion general del dataframe
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 36418 entries, 0 to 36417
Data columns (total 91 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   pl_name          36418 non-null  object
 1   hostname         36418 non-null  object
 2   default_flag     36418 non-null  int64
 3   sy_snum          36418 non-null  int64
 4   sy_pnum          36418 non-null  int64
 5   discoverymethod  36418 non-null  object
 6   disc_year        36418 non-null  int64
 7   disc_facility    36418 non-null  object
 8   soltype          36418 non-null  object
 9   pl_refname       36418 non-null  object
 10  pl_orbper        33247 non-null  float64
 11  pl_orbpererr1    31709 non-null  float64
 12  pl_orbpererr2    31708 non-null  float64
 13  pl_orbperlim     33247 non-null  float64
 14  pl_orbsmax       19990 non-null  float64
 15  pl_orbsmaxerr1   5544 non-null   float64
 16  pl_orbsmaxerr2   5543 non-null   float64
 17  pl_orbsmaxlim    22762 non-null  float64
 18  pl_rade          24836 non-null  float64
 19  pl_radeerr1      24109 non-null  float64
 20  pl_radeerr2      24109 non-null  float64
 21  pl_radelim       27574 non-null  float64
 22  pl_radj          24836 non-null  float64
 23  pl_radjerr1      24109 non-null  float64
 24  pl_radjerr2      24109 non-null  float64
 25  pl_radjlim       24836 non-null  float64
 26  pl_bmasse        6207 non-null   float64
 27  pl_bmasseerr1    5683 non-null   float64
 28  pl_bmasseerr2    5683 non-null   float64
 29  pl_bmasselim     6207 non-null   float64
 30  pl_bmassj        6206 non-null   float64
 31  pl_bmassjerr1    5677 non-null   float64
 32  pl_bmassjerr2    5677 non-null   float64
 33  pl_bmassjlim     6206 non-null   float64
 34  pl_bmassprov     6207 non-null   object
 35  pl_orbeccen      18216 non-null  float64
 36  pl_orbeccenerr1  3395 non-null   float64
 37  pl_orbeccenerr2  3394 non-null   float64
 38  pl_orbeccenlim   20955 non-null  float64
 39  pl_insol         15224 non-null  float64
 40  pl_insolerr1     14085 non-null  float64
 41  pl_insolerr2     14085 non-null  float64
 42  pl_insollim      20267 non-null  float64
 43  pl_eqt           16571 non-null  float64
 44  pl_eqterr1       2137 non-null   float64
 45  pl_eqterr2       2137 non-null   float64
 46  pl_eqtlim        19309 non-null  float64
 47  ttv_flag         36418 non-null  int64
 48  st_refname       36069 non-null  object
 49  st_spectype      2611 non-null   object
 50  st_teff          33449 non-null  float64
 51  st_tefferr1      32697 non-null  float64
 52  st_tefferr2      32390 non-null  float64
 53  st_tefflim       33449 non-null  float64
 54  st_rad           33502 non-null  float64
 55  st_raderr1       27980 non-null  float64
 56  st_raderr2       27795 non-null  float64
 57  st_radlim        33502 non-null  float64
 58  st_mass          30719 non-null  float64
 59  st_masserr1      25311 non-null  float64
 60  st_masserr2      25116 non-null  float64
 61  st_masslim       30719 non-null  float64
 62  st_met           22759 non-null  float64
 63  st_meterr1       22091 non-null  float64
 64  st_meterr2       22091 non-null  float64
 65  st_metlim        25069 non-null  float64
 66  st_metratio      22562 non-null  object
 67  st_logg          29630 non-null  float64
 68  st_loggerr1      24351 non-null  float64
 69  st_loggerr2      24350 non-null  float64
 70  st_logglim       29630 non-null  float64
 71  sy_refname       36418 non-null  object
 72  rastr            36418 non-null  object
 73  ra               36418 non-null  float64
 74  decstr           36418 non-null  object
 75  dec              36418 non-null  float64
 76  sy_dist          35586 non-null  float64
 77  sy_disterr1      34751 non-null  float64
 78  sy_disterr2      34751 non-null  float64
 79  sy_vmag          35698 non-null  float64
 80  sy_vmagerr1      35685 non-null  float64
 81  sy_vmagerr2      35684 non-null  float64
 82  sy_kmag          35686 non-null  float64
 83  sy_kmagerr1      35470 non-null  float64
 84  sy_kmagerr2      35470 non-null  float64
 85  sy_gaiamag       35399 non-null  float64
 86  sy_gaiamagerr1   35399 non-null  float64
 87  sy_gaiamagerr2   35399 non-null  float64
 88  rowupdate        36417 non-null  object
 89  pl_pubdate       36418 non-null  object
 90  releasedate      36418 non-null  object
dtypes: float64(70), int64(5), object(16)
memory usage: 25.3+ MB

In [17]:
# ordenar desc por cantidad de valores nulos
df_sorted = data.isnull().sum().sort_values(ascending=False)
print(df_sorted.head(40))

pl_eqterr2         34281
pl_eqterr1         34281
st_spectype        33807
pl_orbeccenerr2    33024
pl_orbeccenerr1    33023
pl_orbsmaxerr2     30875
pl_orbsmaxerr1     30874
pl_bmassjerr2      30741
pl_bmassjerr1      30741
pl_bmasseerr1      30735
pl_bmasseerr2      30735
pl_bmassjlim       30212
pl_bmassj          30212
pl_bmassprov       30211
pl_bmasselim       30211
pl_bmasse          30211
pl_insolerr2       22333
pl_insolerr1       22333
pl_insol           21194
pl_eqt             19847
pl_orbeccen        18202
pl_eqtlim          17109
pl_orbsmax         16428
pl_insollim        16151
pl_orbeccenlim     15463
st_meterr2         14327
st_meterr1         14327
st_metratio        13856
st_met             13659
pl_orbsmaxlim      13656
pl_radeerr2        12309
pl_radeerr1        12309
pl_radjerr1        12309
pl_radjerr2        12309
st_loggerr2        12068
st_loggerr1        12067
pl_radj            11582
pl_radjlim         11582
pl_rade            11582
st_metlim          11349
dtype: int64

ModuleNotFoundError: No module named 'pandas'